### ISSUE TITLE
how to disable uibuilder default style

### ISSUE THREAD

**Issue by Nash-x9** [newonejoe/node-red-uibuillder-vite-template#2]
thanks for your demo project.
I use `vue3-app` as my starter template.

In this template,uibuilderPlugin was install default,it's not only bring helpful function ,but also change the global css style.

I want to use other UI,how can I remove that?

**Comment by newonejoe** [comment]
In the Vue3-app, there are 2 vue components containing css:  
1) src/App.vue 
```
<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
```

2) src/component/HelloWorld.vue
```
 <style scoped>
a {
  color: #42b983;
}
.container {
  display: inline;
  text-align: center;
}
.box {
  font: 15px arial, sans-serif;
  border-style: solid;
  border-width: 1px;
  padding: 10px;
  border-radius: 5px;
  display: inline-block;
}
.box-topic {
  height: 50px;
  font: 20px bold, arial, sans-serif;
  width: 95%;
  padding: 5px;
}
.box-message {
  height: 200px;
  font: 17px arial, sans-serif;
  width: 95%;
  padding: 5px;
}
</style>
```

You can also write your own css, import in the main.ts; or use UI frameworks such antdv with less.

**Comment by Nash-x9** [comment]
I have read the official documentation, which mentions the default style issue.

So I should add the default stylesheet reference to be used to remove the default styles from uibuilder.

[Auto-loading of the uibuilder default stylesheet](https://totallyinformation.github.io/node-red-contrib-uibuilder/#/uibuilder.module?id=auto-loading-of-the-uibuilder-default-stylesheet)
>
>In previous versions of the front-end library, you had to provide your own CSS code and had to make sure that you imported (or loaded) the uibuilder default stylesheet (uib-styles.css).
>
>In this version, if you haven't loaded any other stylesheets, the library will automatically load the new default stylesheet (uib-brand.css).
```
